Implement Brute Force Solver
TheMuppet/deno-CSP pull request #11
Opened 2022-02-25 12:46 UTC by TheMuppet

2022-02-25 12:53 UTC, alexsc23 approved these changes

2022-02-25 14:13 UTC, xTomsko requested changes
Function "isConsistent" in "backtrackSolver.ts" would be a better fit in "utils.ts".
May need it for other implementations of solvers

2022-02-25 17:49 UTC, xTomsko commented
Please add testing for isConsistent

2022-02-26 17:50 UTC, TheMuppet commented
> Function "isConsistent" in "backtrackSolver.ts" would be a better fit in "utils.ts". May need it for other implementations of solvers

As far as I know, we will not need the "is consistent" function for other solvers. Therefore I would not export it to utils.ts

2022-02-26 18:24 UTC, xTomsko approved these changes

2022-02-26 18:28 UTC, merged